%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.6

-ifndef(protos).
-define(protos, true).

-define(protos_gpb_version, "4.10.6").

-ifndef('SYN_PB_H').
-define('SYN_PB_H', true).
-record('Syn',
        {type                   :: iodata()         % = 1
        }).
-endif.

-ifndef('LOGIN_PB_H').
-define('LOGIN_PB_H', true).
-record('Login',
        {name                   :: iodata(),        % = 1
         pass                   :: iodata()         % = 2
        }).
-endif.

-ifndef('LOGINCONFIRMATION_PB_H').
-define('LOGINCONFIRMATION_PB_H', true).
-record('LoginConfirmation',
        {response               :: boolean() | 0 | 1 % = 1
        }).
-endif.

-ifndef('PRODUCTION_PB_H').
-define('PRODUCTION_PB_H', true).
-record('Production',
        {product_name           :: iodata(),        % = 1
         min                    :: integer(),       % = 2, 32 bits
         max                    :: integer(),       % = 3, 32 bits
         price                  :: float() | integer() | infinity | '-infinity' | nan, % = 4
         data                   :: iodata()         % = 5
        }).
-endif.

-ifndef('NEGOTIATION_PB_H').
-define('NEGOTIATION_PB_H', true).
-record('Negotiation',
        {importer_offer         :: iodata(),        % = 1
         product_name           :: iodata(),        % = 3
         price                  :: float() | integer() | infinity | '-infinity' | nan, % = 4
         amount                 :: integer(),       % = 5, 32 bits
         data                   :: iodata()         % = 6
        }).
-endif.

-ifndef('BUSINESSCONFIRMATION_PB_H').
-define('BUSINESSCONFIRMATION_PB_H', true).
-record('BusinessConfirmation',
        {response               :: boolean() | 0 | 1, % = 1
         zeroMQ                 :: iodata()         % = 2
        }).
-endif.

-ifndef('NEGOTIATIONSCONFIRMATIO_PB_H').
-define('NEGOTIATIONSCONFIRMATIO_PB_H', true).
-record('NegotiationsConfirmatio',
        {acepted = []           :: [protos:'AceptedNegotiation'()] | undefined % = 1
        }).
-endif.

-ifndef('ACEPTEDNEGOTIATION_PB_H').
-define('ACEPTEDNEGOTIATION_PB_H', true).
-record('AceptedNegotiation',
        {importer_offer         :: iodata(),        % = 1
         product_name           :: iodata(),        % = 3
         price                  :: float() | integer() | infinity | '-infinity' | nan, % = 4
         amount                 :: integer(),       % = 5, 32 bits
         data                   :: iodata(),        % = 6
         state                  :: iodata()         % = 7
        }).
-endif.

-ifndef('DROPWIZARD_PB_H').
-define('DROPWIZARD_PB_H', true).
-record('Dropwizard',
        {type                   :: iodata(),        % = 1
         username               :: iodata(),        % = 2
         prod                   :: iodata()         % = 3
        }).
-endif.

-ifndef('RESPONSEDROPPROD_PB_H').
-define('RESPONSEDROPPROD_PB_H', true).
-record('ResponseDropProd',
        {products = []          :: [protos:'Production'()] | undefined % = 1
        }).
-endif.

-endif.
